bom_base_name:               S4HANA_2021_ISS_v0001ms
#kv_name: Name of your Management/Control Plane keyvault

# Set to true to instruct Ansible to update all the packages on the virtual machines
upgrade_packages:              false 

# TERRAFORM CREATED
sap_fqdn:                      sapbasis.com                      
# # kv_name is the name of the key vault containing the system credentials
# kv_name:                       DEVWEEUSAP01user###
# # secret_prefix is the prefix for the name of the secret stored in key vault
# secret_prefix:                 DEV-WEEU-SAP01

# sap_sid is the application SID
sap_sid:                       X00
# scs_high_availability is a boolean flag indicating 
# if the SAP Central Services are deployed using high availability 
scs_high_availability:         false
# SCS Instance Number
scs_instance_number:           "00"
# scs_lb_ip is the SCS IP address of the load balancer in 
# from of the SAP Central Services virtual machines
scs_lb_ip:                     10.110.32.26
# ERS Instance Number
ers_instance_number:           "02"
# ecs_lb_ip is the ERS IP address of the load balancer in
# from of the SAP Central Services virtual machines
ers_lb_ip:                     

# sap_sid is the database SID
db_sid:                        XDB
# platform
platform:                      HANA

# db_high_availability is a boolean flag indicating if the 
# SAP database servers are deployed using high availability
db_high_availability:          false
# db_lb_ip is the IP address of the load balancer in from of the database virtual machines
db_lb_ip:                      10.110.96.13

disks:
  - { host: 'saphdb1', LUN: /dev/vdg, type: 'sap' }
  - { host: 'saphdb1', LUN: /dev/vdb, type: 'data' }
  - { host: 'saphdb1', LUN: /dev/vdc, type: 'data' }
  - { host: 'saphdb1', LUN: /dev/vdd, type: 'log' }
  - { host: 'saphdb1', LUN: /dev/vde, type: 'log' }
  - { host: 'saphdb1', LUN: /dev/vdf, type: 'shared' }

_workspace_directory: /anganch1_ansible/workspace